name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install virtualenv
      run: python -m pip install virtualenv

    - name: Create and activate virtual environment
      run: python -m virtualenv .env

    - name: Install dependencies
      run: .env/bin/pip install -r requirements.txt

    - name: Run tests
      run: echo "Running tests" # Replace with actual test command

    - name: Build Docker image
      run: echo "Compiling docker image" 